CREATE TABLE IF NOT EXISTS user (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  pwd TEXT NOT NULL,
  pwd_salt TEXT NOT NULL,
  token_salt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS celestial_body (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);